stages:
  data_ingestion:
    cmd: python src/data/data_ingestion.py
    deps:
    - src/data/data_ingestion.py
    outs:
    - data/raw
  data_preprocessing:
    cmd: python src/data/data_preprocess.py
    deps:
    - data/raw
    - src/data/data_preprocess.py
    outs:
    - data/processed
  feature_engineering:
    cmd: python src/features/feature_engineering.py
    deps:
    - data/processed
    - src/features/feature_engineering.py
    outs:
    - data/features

  model_building:
    cmd: python src/model/model_building.py
    deps:
    - data/features
    - src/model/model_building.py
  model_evaluation:
    cmd: python src/model/model_evaluation.py
    deps:
    - models/model.pkl
    - src/model/model_evaluation.py
